apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-vaultkubenertes-job
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manufacturer-vaultkubenertes-job
  chart:
    git: https://github.com/masdelmon72/bevel.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
    secretRef:
      name: gitcredentials
  values:
    metadata:
      name: manufacturer
      component_type: peer
      namespace: manufacturer-net    
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://10.100.181.78:32000
      authpath: devmanufacturer-net-auth
      policy: vault-crypto-peer-manufacturer-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://33D996E62F6FC321C07BAFFF48CDF349.gr7.eu-central-1.eks.amazonaws.com
