kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storesc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - "eu-central-1a"
    - "eu-central-1b"
