apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-vaultkubenertes-job
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-vaultkubenertes-job
  chart:
    git: https://github.com/masdelmon72/bevel.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
    secretRef:
      name: gitcredentials
  values:
    metadata:
      name: supplychain
      component_type: orderer
      namespace: supplychain-net    
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://10.100.181.78:32000
      authpath: localsupplychain-net-auth
      policy: vault-crypto-orderer-supplychain-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://33D996E62F6FC321C07BAFFF48CDF349.gr7.eu-central-1.eks.amazonaws.com
